// This file is generated by Slice Machine. Update with care!

import HomeSlice from './HomeSlice';
import NewSlice from './NewSlice';
import TextBlock from './TextBlock';

export {
	HomeSlice,
	NewSlice,
	TextBlock,
};

export const components = {
	home_slice: HomeSlice,
	new_slice: NewSlice,
	text_block: TextBlock,
};
