// This file is generated by Slice Machine. Update with care!

import HeroFeaturedImage from './HeroFeaturedImage';
import HomeSlice from './HomeSlice';
import Image from './Image';
import NewSlice from './NewSlice';
import TextBlock from './TextBlock';

export {
	HeroFeaturedImage,
	HomeSlice,
	Image,
	NewSlice,
	TextBlock,
};

export const components = {
	hero_featured_image: HeroFeaturedImage,
	home_slice: HomeSlice,
	image: Image,
	new_slice: NewSlice,
	text_block: TextBlock,
};
