// This file is generated by Slice Machine. Update with care!

import HomeSlice from './HomeSlice';
import TextBlock from './TextBlock';

export {
	HomeSlice,
	TextBlock,
};

export const components = {
	home_slice: HomeSlice,
	text_block: TextBlock,
};
